from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    asset_symbol: Annotated[str, "Crypto asset or pair that we are interested in trading"]
    trade_date: Annotated[str, "What analysis timestamp we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Structure Analyst"]
    sentiment_report: Annotated[str, "Report from the Volume Flow Analyst"]
    funding_oi_report: Annotated[str, "Report from the Funding & OI Analyst"]
    news_report: Annotated[
        str, "Report from the Crypto Catalyst Analyst"
    ]
    tokenomics_report: Annotated[str, "Report from the Tokenomics & On-Chain Analyst"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]
    setup_classification: Annotated[str, "Setup classification generated by the Decision Team"]
    decision_plan: Annotated[str, "Formal decision recommendation generated by the Decision Team"]

    trader_investment_plan: Annotated[str, "Execution plan generated by the Execution Team"]
    trade_risk_assessment: Annotated[
        str, "Per-trade risk assessment generated by the Trade Risk Analyst"
    ]
    portfolio_risk_assessment: Annotated[
        str,
        "Portfolio-level risk assessment generated by the Portfolio Risk Analyst",
    ]
